feat: add toml pip package installation

diff --git a/home/.chezmoiscripts/run_onchange_before_02-playbook.sh.tmpl b/home/.chezmoiscripts/run_onchange_before_02-playbook.sh.tmpl
--- a/home/.chezmoiscripts/run_onchange_before_02-playbook.sh.tmpl
+++ b/home/.chezmoiscripts/run_onchange_before_02-playbook.sh.tmpl
@@ -4,6 +4,35 @@ source {{ joinPath .chezmoi.sourceDir "/helpers/logger.sh" | quote }}
 
 PACKAGE_MANAGER="{{- template "pkg_manager" . -}}"
 
+install_pip_deps() {
+    # To avoid "externally-managed-environment" error
+    if [ $PACKAGE_MANAGER = "pacman" ]; then
+        sudo pacman -S python-toml --needed
+        return 0
+    fi
+
+    if [ ! command -v pip3 &> /dev/null ]; then
+        log_info "pip3 not found. Installing pip for Python 3..."
+        curl -fsLS https://bootstrap.pypa.io/get-pip.py | python3
+        if [ $? -ne 0 ]; then
+            log_error "Failed to install pip. Exiting..."
+            exit 1
+        fi
+    else
+        log_warn "pip3 is already installed."
+    fi
+
+    log_info "Installing toml package..."
+    python3 -m pip3 install toml
+
+    if [ $? -eq 0 ]; then
+        log_success "toml package installed successfully"
+    else
+        log_error "Failed to install toml package"
+        exit 1
+    fi
+}
+
 run_playbook() {
     log_info "Running ansible playbook"
     if command -v ansible-playbook &> /dev/null; then
@@ -14,6 +43,7 @@ run_playbook() {
 if [ $PACKAGE_MANAGER = "unknown" ]; then
     log_error "Current system's package manager is unsupported. Unable to install packages via ansible. Skipping..."
 else
+    install_pip_deps
     run_playbook
 fi
 
